SELECT DISTINCT room
,coursetitle 
FROM students 
WHERE coursetitle NOT LIKE '%AcademicMentor%'   
AND coursetitle NOT LIKE '%Academic Mentor%'   
AND coursetitle NOT LIKE '%Supervention%'   
AND coursetitle NOT LIKE '%Cond%'   
AND coursetitle NOT LIKE '%CT%'   
AND coursetitle NOT LIKE '%GCC%'   
AND coursetitle NOT LIKE '%LAVC%'   
AND coursetitle NOT LIKE BINARY '%TA%'   
AND coursetitle NOT LIKE '%TA/%'   
AND coursetitle NOT LIKE '%Tm%'   
AND coursetitle NOT LIKE '%CTF%'   
AND coursetitle NOT LIKE '%Unsched Per 0%'   
AND coursetitle NOT LIKE '%PE%'                   
-- AND period < 7
-- AND room NOT LIKE '%Office%'                    
-- AND room NOT LIKE '%1217%'                      
-- AND room NOT LIKE '%7003%'                      
-- AND room NOT LIKE '%2306%'                      
-- AND room NOT LIKE '%2217%'
-- AND room NOT LIKE '%2202%'                      
-- AND room NOT LIKE '%2113%'                      
-- AND room NOT LIKE '%9104%'                      
-- AND room NOT LIKE '%6203%'                      
-- AND room NOT LIKE '%9102%'                        
-- AND room NOT LIKE '%1153%'                      
-- AND room NOT LIKE '%2309%'
-- AND room NOT LIKE '%1211%'                      
-- AND room NOT LIKE '%1213%'                      
-- AND room NOT LIKE '%1154%'                      
-- AND room NOT LIKE '%1235%'                      
-- AND room NOT LIKE '%7114%'
-- AND room NOT LIKE '%2307%'                      
-- AND room NOT LIKE '%1150%'                      
-- AND room NOT LIKE '%2206%'                      
-- AND room NOT LIKE '%6107%'                      
-- AND room NOT LIKE '%2228%'
-- AND room NOT LIKE '%1224%'                      
-- AND room NOT LIKE '%1216%'
-- AND room NOT LIKE '%1149%'           
-- AND room NOT LIKE '' 
order by room asc, coursetitle asc